[workspace]
members = [ "examples/*" ]
exclude = []
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Nadhmi JAZI <nadhmi.eljazi@gmail.com>"]
edition = "2021"
license = "MIT license"
repository = "https://github.com/jazi007/rust-examples"
