[package]
name = "chat_app"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
once_cell = "1.19.0"
tokio = { version = "1.35.1", features = ["full"] }
